x-agents-defaults: &agent-defaults
  build:
    context: ./agents
    dockerfile: Dockerfile
  working_dir: /app
  entrypoint: ["/bin/sh", "/app/register-agent.sh"]
  networks:
    - shared_agents_net
  restart: "on-failure:5"
  logging:
    driver: "json-file"
    options:
      max-size: "50m"
      max-file: 5
 
services:

  # Nuzlocke Planner Agent
  register-agent-nuzlocke-planner:
    <<: *agent-defaults
    container_name: register-agent-nuzlocke-planner
    volumes:
      - ./agents/planner:/app/model:ro
      - ./agents/register-agent.sh:/app/register-agent.sh:ro
    environment:
      - AGENT_NAME=ai-pokemon/agent-nuzlocke-planner
      - MODELFILE_PATH=/app/model/Modelfile
      - OLLAMA_HOST=http://ollama:11434

  # Nuzlocke Battle Agent
  register-agent-nuzlocke-battle:
    <<: *agent-defaults
    container_name: register-agent-nuzlocke-battle
    volumes:
      - ./agents/battle:/app/model:ro
      - ./agents/register-agent.sh:/app/register-agent.sh:ro
    environment:
      - AGENT_NAME=ai-pokemon/agent-nuzlocke-battle
      - MODELFILE_PATH=/app/model/Modelfile
      - OLLAMA_HOST=http://ollama:11434

  # Nuzlocke Strategy Agent
  register-agent-nuzlocke-strategy:
    <<: *agent-defaults
    container_name: register-agent-nuzlocke-strategy
    volumes:
      - ./agents/strategy:/app/model:ro
      - ./agents/register-agent.sh:/app/register-agent.sh:ro
    environment:
      - AGENT_NAME=ai-pokemon/agent-nuzlocke-strategy
      - MODELFILE_PATH=/app/model/Modelfile
      - OLLAMA_HOST=http://ollama:11434

  # Nuzlocke Composer Agent
  register-agent-nuzlocke-composer:
    <<: *agent-defaults
    container_name: register-agent-nuzlocke-composer
    volumes:
      - ./agents/composer:/app/model:ro
      - ./agents/register-agent.sh:/app/register-agent.sh:ro
    environment:
      - AGENT_NAME=ai-pokemon/agent-nuzlocke-composer
      - MODELFILE_PATH=/app/model/Modelfile
      - OLLAMA_HOST=http://ollama:11434

networks:
  shared_agents_net:
    external: true
    name: shared_agents_net
